apiVersion: apps/v1
kind: Deployment
metadata:
  name: yts-credit-scoring-app
spec:
  template:
    spec:
      containers:
        - name: yts-credit-scoring-app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: team,$(ENVIRONMENT),$(NAMESPACE),$(ENVIRONMENT)-$(NAMESPACE)
