spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ""
            clientSecret: ""
            redirectUri: "http://localhost:3000/admin/oauth2/callback/{registrationId}"
