apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  name: yts-credit-scoring-app
configurations:
  - var-ref.yaml
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
vars:
  - name: NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: yts-credit-scoring-app
    fieldref:
      fieldpath: metadata.namespace
