apiVersion: v1
kind: Service
metadata:
  name: yts-credit-scoring-app
  labels:
    team: yts-apps
spec:
  selector:
    name: yts-credit-scoring-app
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
